const ERROR_TYPES = {
  CAMERA_FAILURE: "CAMERA_FAILURE",
  SENSOR_FAILURE: "SENSOR_FAILURE",
  ACTUATOR_FAILURE: "ACTUATOR_FAILURE",
  COMMUNICATION_FAILURE: "COMMUNICATION_FAILURE",
  EMERGENCY_STOP: "EMERGENCY_STOP",
  CLASSIFICATION_ERROR: "CLASSIFICATION_ERROR",
  SYSTEM_ERROR: "SYSTEM_ERROR",
};

const ERROR_TYPE_LIST = Object.values(ERROR_TYPES);

module.exports = { ERROR_TYPES, ERROR_TYPE_LIST };